### ISSUE TITLE
Custom door labels and third door

### ISSUE THREAD

**Issue by jefsocmw** [rjcohn/alexa-pymyq#16]
Thank you for making this update. I was able to get the skill working after being broken for several months. I would like to use a custom name and also add a third door that could also be a gate. Is this possible?

**Comment by rjcohn** [comment]
You can easily change the door names in interaction_model.json (search for left and right). You'll have to go to the JSON editor and after making a change, click Build Model again.
Adding a third door or gate would require a code change. The best thing to do, if you're comfortable with it, is to fork the repo and add the code for the third door. Sorry I can't be more help there.

**Comment by rjcohn** [comment]
Closing the issue for now. If you do fork and make a PR, I'm happy to review it. I won't be able to test changes for 3 doors, so I'm not sure how to deal with that.
