### ISSUE TITLE
Open Garage Not Working

### ISSUE THREAD

**Issue by molonlabe88** [rjcohn/alexa-pymyq#20]
When I perform "alexa ask my garage left to open" I get "I didn't understand that. You can say open or close the left or right door."

I have the value set to 'N' to permit the garage to open. 

Any ideas?

**Comment by dabadgreek** [comment]
I am getting this as well. I can get status on either door, or both via what's up, I can open left but get same error on close left, open right or close right.

**Comment by rjcohn** [comment]
I'm sorry. I updated to a new pymyq, which had a bug. I see the same problem myself. This weekend, I will pick up the newer pymyq, and if that doesn't work, revert to the older one.

**Comment by dabadgreek** [comment]
rjcohn thank you!

**Comment by rjcohn** [comment]
Please try with the latest code. Unfortunately, opening and closing works locally with 3.1.2 but fails via Alexa. However, 3.0.4 seems to work fine, either way, so I've reverted to it. If one or both of @molonlabe88 @dabadgreek confirm it's working, I'll close this.

**Comment by dabadgreek** [comment]
@rjcohn thank you for addressing this so quickly. Sorry for the newbie question, to be clear are you saying you backleveled the pymyq to 3.0.4 and if so i need to redownload the code and upload the lambda_update.zip zip and upload it back to aws and go through the build process again. Is that right? Thanks

**Comment by rjcohn** [comment]
You do need to upload lambda-upload.zip to the AWS Console, but that's it. No additional build step is needed.

One change I made last night is that I tried to clarify instructions for doing that at the bottom of the README. Let me know if the instructions are clear and if it works for you.

**Comment by dabadgreek** [comment]
@rjcohn was able to get it working. Thanks so much for the excellent work. One question I can open and close left or right garage and get status, when I ask to open or close both it only opens or closes left (primary) door. Outside of that working perfectly. Thanks.

**Comment by rjcohn** [comment]
Sorry. It's working for me: "Alexa, ask garage to open both doors" (or close). If you go into the logs (see my last update to the README under "Updating Alexa-PyMyQ" for how to do this if you're unfamiliar with it), it would be helpful to send me the invocation information. It will look like this:
```
"request": {"type": "IntentRequest", "requestId": "amzn1.echo-api.request.749d83c6-c5a9-496d-b681-f2fb5d0a8698", "locale": "en-US", "timestamp": "2021-08-18T13:53:54Z", "intent": {"name": "MoveIntent", "confirmationStatus": "NONE", "slots": {"Command": {"name": "Command", "value": "close", "resolutions": {"resolutionsPerAuthority": [{"authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.fca3bd79-8dfc-4a86-aa3b-1df857d5d315.DoorCommand", "status": {"code": "ER_SUCCESS_MATCH"}, "values": [{"value": {"name": "close", "id": "close"}}]}]}, "confirmationStatus": "NONE", "source": "USER", "slotValue": {"type": "Simple", "value": "close", "resolutions": {"resolutionsPerAuthority": [{"authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.fca3bd79-8dfc-4a86-aa3b-1df857d5d315.DoorCommand", "status": {"code": "ER_SUCCESS_MATCH"}, "values": [{"value": {"name": "close", "id": "close"}}]}]}}}, "Name": {"name": "Name", "value": "both doors", "resolutions": {"resolutionsPerAuthority": [{"authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.fca3bd79-8dfc-4a86-aa3b-1df857d5d315.DoorName", "status": {"code": "ER_SUCCESS_MATCH"}, "values": [{"value": {"name": "both", "id": "both"}}]}]}, "confirmationStatus": "NONE", "source": "USER", "slotValue": {"type": "Simple", "value": "both doors", "resolutions": {"resolutionsPerAuthority": [{"authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.fca3bd79-8dfc-4a86-aa3b-1df857d5d315.DoorName", "status": {"code": "ER_SUCCESS_MATCH"}, "values": [{"value": {"name": "both", "id": "both"}}]}]}}}}}}
```
It should be the second or third line of the log for your command. You will need to set the LOG_LEVEL to DEBUG in the Environment Variables section of Configuration if you haven't done that before.

**Comment by rjcohn** [comment]
Closing this issue. If @dabadgreek or anyone else is still having problems with opening/closing both doors or anything else, please open a new issue.
