### ISSUE TITLE
Unable to deploy the code. Getting error "Deployment Failed. There could be another build running on the account. Please try again. "

### ISSUE THREAD

**Issue by rjberm** [rjcohn/alexa-pymyq#8]
I get this error when I follow the instructions. Any reasons behind this?

**Comment by rjcohn** [comment]
Are there any additional error messages? 
If you can share your updated .env file *without* the password, that might be a clue. 
See also https://forums.developer.amazon.com/questions/226061/code-deployment-has-failed-there-could-be-another.html
You could file a case with Amazon if we can't figure it out here.

**Comment by rjberm** [comment]
Thank you for the response! Here are the details
.env file
`USER_NAME=
PASSWORD=
ONLY_CLOSE=N
LEFT=0`

requirements file
`aiohttp~=3.7.3
environs~=9.3.1
pymyq~=3.0.4
pytest~=6.2.2
pytest-mock~=3.5.1
boto3==1.9.216
ask-sdk-core==1.11.0`

all files reside within the lambda folder

I get this error in the log

`Collecting aiohttp~=3.7.3 Downloading aiohttp-3.7.3-cp37-cp37m-manylinux2014_x86_64.whl (1.3 MB) Collecting environs~=9.3.1 Downloading environs-9.3.1-py2.py3-none-any.whl (11 kB) ERROR: Could not find a version that satisfies the requirement pymyq~=3.0.4 (from -r requirements.txt (line 3)) (from versions: 0.0.8, 0.0.11, 0.0.15, 0.0.16, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 3.0.0, 3.0.1, 3.0.2, 3.0.3) ERROR: No matching distribution found for pymyq~=3.0.4 (from -r requirements.txt (line 3)) WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available. You should consider upgrading via the '/var/lang/bin/python3.7 -m pip install --upgrade pip' command.`

`Pip failed to install dependencies! Something wrong in your requirements.txt file!`

It says that it can't find pymyq~=3.0.4?

**Comment by rjcohn** [comment]
Unfortunately, pymyq now requires Python 3.8, but the Alexa hosted Python skill only supports Python 3.7. If you are familiar with setting up a skill using AWS Lambda, then you can choose Python 3.8 there. I'm actually running my version of the skill that way. If you want to do that, I can retrieve the instructions from an older version. I had changed the documentation here to use the hosted skill because the setup is simpler. Let me know.

**Comment by waffles0042** [comment]
First off, thanks for posting this @rjcohn! 
I have been following your instructions but keep getting the same error message. It would be awesome if you could retrieve those instructions to make it work again.

**Comment by rjcohn** [comment]
I'll do that, but I won't be able to get to it until early next week.

**Comment by waffles0042** [comment]
Thank you @rjcohn, much appreciated!

**Comment by waffles0042** [comment]
Hello @rjcohn; I was wondering if you had any chance to look into it yet. Thanks much!

**Comment by rjcohn** [comment]
Sorry for the delay. I've updated the instructions and tested them out. They are a lot more complicated now. Please let me know if you are successful or if you run into issues. I'll close this issue, but please open another if you do find problems with the README.

**Comment by waffles0042** [comment]
@rjcohn Your instructions worked perfectly. Step by step - all very well documented! Perfect! Thank you very, very much!
